### ISSUE TITLE
Speed things up

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#10]
**Is your feature request related to a problem? Please describe.**
I keep trying to test this but it takes a while to get to the error.

**Describe the solution you'd like**
I would like the loading and dialog writing to be sped up.

**Describe alternatives you've considered**
Having a thing in preferences?

**Additional context**
N/A

**Comment by OcelotWalrus** [comment]
I'll add a preferences so you skip loading menu and dialog are are instantaneous.

**Comment by OcelotWalrus** [comment]
f130ed470274881195e6764010cc1b65a02b001c
