### ISSUE TITLE
FEATURE: Mounts Feeding Needs

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Bane-Of-Wargs#104]
### Is your feature request related to a problem? Please describe.

Mounts are too easy to sustain: once you have one and start using it, there's no way it's gonna die or run away for some reasons. This should be fixed by adding new petting features to mounts.

### Describe the solution you'd like

Mounts will have a health stat that goes down a bit every day (about 5%). Each different type of mount will have a different health stat and a different rate of health loss depending on their already-existing feeding needs stat. They will also lose a certain amount of health when ending a fight. This amount will vary depending on the number of enemies in that fight. Finally, a mount's health will also go down when training in a stabling.

To restore its health, the player will have to let the mount rest in a stable for an amount of time depending on the health to restore.

### Describe alternatives you've considered

N/A

### Additional context

Please feel free to suggest anything @lumbar527.

**Comment by TheGiraffe3** [comment]
Remove `help wanted` label?

**Comment by lumbar527** [comment]
I don't know exactly what Cromha wants but I would say it doesn't matter, seeing as the issue is closed.
