### ISSUE TITLE
Don't use "Kathallion" so much

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#12]
**Is your feature request related to a problem? Please describe.**
I sort of have some idea of who Kathallion is—he's a bad guy. His name is used very much in Bane of Wargs.

**Describe the solution you'd like**
I would like there to be a different name instead of Kathallion that is used throughout Bane of Wargs.

**Describe alternatives you've considered**
Note sure what you have planned for Bane of Wargs, but maybe it could be set before Dungeons-of-Kathallion, while Lord Kathallion still had power.

**Additional context**
N/A

**Comment by OcelotWalrus** [comment]
Sure! It's just a placeholder now.

**Comment by lumbar527** [comment]
A change has not been made yet and we can discuss naming here, so I'm reopening.

**Comment by lumbar527** [comment]
Need some help with naming?

**Comment by OcelotWalrus** [comment]
Not but thanks! Don't worry the current vanilla plot is just for testing mechanics. I'll work on the vanilla plot when the game engine will be finished.I already have some ideas for it.
