### ISSUE TITLE
BUG: Windows Compiled Program Compatability

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Bane-Of-Wargs#21]
**Describe the bug**
When downloading the compiled `.exe` program from the [continuous build](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/releases/tag/9.9.9-continuous), after launching it you get an error with the `fcntl` module not found (in my case, I'm using wine).

Error:
```shell
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "battle.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "term_menu.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "simple_term_menu.py", line 39, in <module>
NotImplementedError: "Windows" is currently not supported.
[292] Failed to execute script 'main' due to unhandled exception!
```

**To Reproduce**
1. Go to 'https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/releases/tag/9.9.9-continuous'
2. Click on 'Bane-Of-Wargs.exe'
3. Run program in terminal

**Expected behavior**
Program should run smoothly with no issues.

**Comment by OcelotWalrus** [comment]
The problem is that there is no `fcntl` module mention on the game source code or in the `cd.yaml` workflow file!

**Comment by lumbar527** [comment]
This problem appears on mac building from the sh file.

**Comment by OcelotWalrus** [comment]
> This problem appears on mac building from the sh file.

Thanks for reporting that!

**Comment by OcelotWalrus** [comment]
Hey @lumbar527, could you tell me if installing the `fcntl` module from pip and after re-compiling the program solve your issue?

**Comment by OcelotWalrus** [comment]
> ```shell
> File "enquiries\__init__.py", line 2, in <module>
> File "PyInstaller\loader\pyimod02_importers.py", line 419, in 
> File "enquiries\yesno.py", line 3, in <module>
> File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
> File "curtsies\__init__.py", line 4, in <module>
> File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
> File "curtsies\window.py", line 24, in <module>
> File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
> File "blessings\__init__.py", line 7, in <module>
> ```
> 
> If I'm following the indications, in line 2 of `main.py` it's written 'import battle', in line 6 of `battle.py`, it's written 'import enquiries'. So the problem is the enquiries module? Maybe the enquiries module requires also fcntl? But since @lumbar527 and the github workflow doesn't have fcntl installed when compiling, it's not packaged with the program?

If I'm following even more, I find in `enquiries/__init__.py` of the enquiries module at line 2 'from enquiries.yesno import confirm'. In `enquiries/yesno.py`, at line 3 'from curtsies import Input, FSArray , CursorAwareWindow, fsarray'. In `curtsies/__init__.py`, at line 4 'from .window import FullscreenWindow, CursorAwareWindow'. In `curtsies\window.py`, at line 24 'import sys'.
And finally in `blessings\__init__.py`, at line 7 'from fcntl import ioctl'.

So yeah, the source of the problem is the enquiries modules which requires other modules that themselves requires the `fcntl` module.

**Comment by OcelotWalrus** [comment]
So here's what I've found:
* Linux: `fcntl` is already built-in in python installation
* MacOS: `fcntl` can be installed
* Windows: `fcntl` isn't compatible

So if I'm correct, to fix the mac problem, or @lumbar527's problem, the `$ pip install fcntl` just needs to be ran before compiling.

**Comment by OcelotWalrus** [comment]
I've made a branch [`enquiries-alternative`](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/tree/enquiries-alternative), which replace the `enquiries` module by an alternative solution. Could you try compiling the program again but with that branch?

Don't forget to run:
```shell
pip install -r requirements.txt # install new modules

python -m PyInstaller \
--console \
--onefile \
--name Bane-Of-Wargs \
source/main.py \
source/battle.py \
source/check_yaml.py \
source/colors.py \
source/map_item.py \
source/train.py \
source/logger_sys.py \
source/term_menu.py \
--add-data yamale/VERSION:yamale \
--collect-submodules fsspec \
--collect-submodules appdirs \
--hidden-import appdirs \
--hidden-import fsspec \
--exclude-module fcntl \
--log-level DEBUG
```

**Comment by OcelotWalrus** [comment]
So, with the code changes I made in branch [`enquiries-alternative`](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/tree/enquiries-alternative), it adds support for Mac (@lumbar527 ). But it still doesn't support Windows.

But I'll still going to make a PR (#23 ) and merge it. Please @lumbar527 could you review it?
