### ISSUE TITLE
Problems when attempting to use `compile.sh`

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#22]
**Describe the bug**
There is an error when I run `compile.sh`. The `--add-data yamale/VERSION:yamale` line returns an error. Removing it has been attempted but it is necessary.

**To Reproduce**
1. Download Bane-of-Wargs.
2. Run `compile.sh`. (I ran copied out and ran everything by pasting.)

**Expected behavior**
I expected the program to compile successfully.

**Save file**
n/a

**Log File**
n/a

**Version**
256ef951e3f5ab6782782afb57048f943a1809dd

**Additional context**
The particular error was:
```
Unable to find '[Path removed for privacy]/Bane-Of-Wargs/yamale/VERSION' when adding binary and data files.
```
(after running the entire command) and
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "check_yaml.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "yamale/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "yamale/version.py", line 6, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/k9/8nfc1g3d683691tqwtpbxscr0000gn/T/_MEIqTC9VF/yamale/VERSION'
[49682] Failed to execute script 'main' due to unhandled exception!
``` (after running the command without the `--add-data yamale/VERSION:yamale` line)
My OS is MacOS Catalina.

**Comment by OcelotWalrus** [comment]
Please check https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/blob/master/docs/BUILDING.md and if it still doesn't solve the problem, please tell me.

**Comment by OcelotWalrus** [comment]
By the way about that the compiled program is a linux executable, just run the command with your macos terminal. If think it's generating a linux executable because you ran the compile command through a bash environment.

**Comment by OcelotWalrus** [comment]
Maybe try 
```python
pip3 install PyInstaller
```

Maybe it's a path problem. But why you're running commands in a virtual bash shell? Just use your default environment of mac.

**Comment by lumbar527** [comment]
The script won't work but copying the command and running it will.

The errors are still both a problem, even though I think I'm running in my local environment.

**Comment by OcelotWalrus** [comment]
> The script won't work but copying the command and running it will.

That's because bash scripts are meant for linux.

**Comment by OcelotWalrus** [comment]
I did some modifications to the [`compile.sh`](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/blob/master/compile.sh) script: I added `!/bin/sh`. Maybe it will help for mac users.

**Comment by OcelotWalrus** [comment]
And also, does the program still compiles as a linux executable?

**Comment by lumbar527** [comment]
It still compiles as a Unix executable.

I can't seem to run the complied file though.

**Comment by OcelotWalrus** [comment]
![image](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/assets/87318892/a235147f-09e5-4e5c-b793-5fcb3807d7be)

**Comment by lumbar527** [comment]
Huh, I guess it did run put it took forever. Then I got errors related to not having `fcntl`. (I mentioned this on the issue about `fcntl` not being found.)

**Comment by OcelotWalrus** [comment]
So, I'm closing this issue.

**Comment by OcelotWalrus** [comment]
Just check the [BUILDING Instructions](https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/blob/master/docs/BUILDING.md)!

If you still doesn't understand at this point:
You need the `--add-data yamale/VERSION:yamale` option in the command and before running it, you must create a directory in the root repository called 'yamale' and then add a file in it called 'VERSION' with written in it, `4.0.4`.
