### ISSUE TITLE
`preferences.yaml` keeps being updated

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#5]
**Describe the bug**
When someone wants to download the game, they get already-set preferences—@OcelotWalrus's.

**To Reproduce**
1. Open the `preferences.yaml` file.

**Expected behavior**
I expected it to not be updated to @OcelotWalrus's preferences.

**Save file**
Please add your save file here.

**Version**
What is your version of Dungeons of Kathallion? [i.e., commit x or release version x]

**Additional context**
SUGGESTION: In one commit, set it to the defaults and add it to the gitignore so it doesn't get updated.

**Comment by OcelotWalrus** [comment]
> Additional context
SUGGESTION: In one commit, set it to the defaults and add it to the gitignore so it doesn't get updated.

I tried but when I add `preferences.yaml\ or `**/preferences.yaml` in the .gitignore file, it don't get ignored.

**Comment by lumbar527** [comment]
I think I fixed it in 6383ccaaeb8eb0ea06652b290ea31949e1ad7094. There no longer is a `preferences.yaml` file!

**Comment by OcelotWalrus** [comment]
Thanks! I'm going to test it out.

**Comment by OcelotWalrus** [comment]
It works well.
