### ISSUE TITLE
@OcelotWalrus, could you use my commit format?

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#6]
**Where is the issue**
The comments

**What the issue is**
The commit names are not clear and do not follow the Contributing Guidelines. For example, you say `Fixes` a lot, rather than `bugfix - this thing`

**Expected content**
I expected the commits to follow the Contributing Guidelines

**Additional Content**
If you want to make an explanation or argument, do so. This commit naming thing is kind of just for fun.

**Comment by OcelotWalrus** [comment]
Sure I'll start using your 'syntax' in the next push! I totally understand that you want the commits comments to be clear.
