### ISSUE TITLE
FEATURE: Selling Zones Discounts

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Bane-Of-Wargs#68]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

I've just gotten an idea: what if selling zones like hostels, stables, blacksmiths and forges could have occasional discounts? Let me explain how this would work:

```python
Any Map Zone:
  [other keys]
  ...
  discounts:
    time space: 18
    chance: .3  # 30%
    discount:
      max discount dropoff: .5  # -50%
      min discount dropoff: .15  # -15%
```

So there'd be a new optional discount dictionary:
* `time space` // the spacing in game days that a discount could possibly append at this map zone.
* `chance` // the chance percentage of the discount to actually append each `time space` game days.
* discount
  * `max discount dropoff` // the maximum dropoff percentage that could append
  * `min discount dropoff` // the minimum dropoff percentage that could append

And it would be actually easy to apply the dropoff (there wouldn't too much code changes in every map zone buying loops): the dropoff will be mixed to the cost value!

---

To display that discount, right above the `NEW` tab, in every interactive map zone, there would be something look kinda like this: (with colors of course ;))

```
=======================================================
NEWS:
Hey! Did you ever heard about tamed Wargs? Seems crazy 
right?
!!!SPECIAL DISCOUNT!!!
A -35% dropoff on every item's happening at the
<map zone> store! Only <in-game hours> hours remains!
!!!SPECIAL DISCOUNT!!!
=======================================================

```

### Describe alternatives you've considered

N/A

### Additional context

This will be coded in the few next PR.

**Comment by lumbar527** [comment]
May I suggest some implementation?
In the save file, there could be a list of store-type things and a number. Every time the number hits 0, discounts start. For the discount to last multiple days, the number could be reset at a negative number. Every day that passed will cause the number to go down.
When resetting, just set the number to a random number around the `time space` value.

**Comment by OcelotWalrus** [comment]
> May I suggest some implementation? In the save file, there could be a list of store-type things and a number. Every time the number hits 0, discounts start. For the discount to last multiple days, the number could be reset at a negative number. Every day that passed will cause the number to go down. When resetting, just set the number to a random number around the `time space` value.

Sorry but I don't really understand very much what you explain here. You could maybe make an example of the new save file key, or something like that? To illustrate what you're proposing :)

**Comment by lumbar527** [comment]
```
<save name>:
  ...
  discount times:
    <this place>: 13 # countdown to sale in hours or days 
    <that place>: -1 # There is a discount now and it started one <whatever unit I'm using> ago.
```

**Comment by OcelotWalrus** [comment]
Ooh! I see what you've meant. That's actually how I kinda already thought

**Comment by OcelotWalrus** [comment]
I think I'll code this after implementing the difficulty modes.

**Comment by OcelotWalrus** [comment]
Progress's happening #83 !
