### ISSUE TITLE
Warg fur does not exist

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#7]
**Describe the bug**
They player is wearing Warg Fur, which is not in the data file.

**To Reproduce**
1. Run Bane-of-Wargs
3. make a new save
5. See error

**Expected behavior**
I expected Warg Fur to exist

**Save file**
Not needed; problem occurs with new save.

**Version**
What is your version of Bane of Wargs? commit dc197e01e2478b09200dd8be04a5b3a76227b84d

**Additional context**
N/A

**Comment by OcelotWalrus** [comment]
Sorry, it's supposed to be `Wolf Fur` and to `Warg Fur`. I'll fix that with next push.
