### ISSUE TITLE
More errors: mounts this time

### ISSUE THREAD

**Issue by lumbar527** [Dungeons-of-Kathallion/Bane-Of-Wargs#8]
**Describe the bug**
```
  File "/Users/tabris/repos/roger/Bane-Of-Wargs/main.py", line 866, in run
    if player["current mount"] in player["mounts"]:
KeyError: 'current mount'
```
I think it's from the fact that mounts are not in the data file.

**To Reproduce**
1. Run the game
2. Create new save

**Expected behavior**
I expected there not to be this error

**Save file**
Any new save

**Version**
What is your version of Bane of Wargs? commit dc197e01e2478b09200dd8be04a5b3a76227b84d

**Additional context**
Have you tested this game?

**Comment by OcelotWalrus** [comment]
Should be fixed by next push.
